name: CI Pipeline for SQL Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: "YourStrong!Passw0rd"
        ports:
          - 1433:1433
        options: > 
          --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'YourStrong!Passw0rd' -Q 'SELECT 1'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=10

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Wait for SQL Server to be ready
      run: |
        sleep 30

    - name: Run all SQL queries in the basic folder
      run: |
        for file in basic/*.sql; do
          /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "YourStrong!Passw0rd" -i "$file"
        done
